In [121]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
files = ["../cleaned_data/unzipped_data/PUDF_base1_4q2019_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_3q2019_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_2q2019_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_1q2019_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_4q2018_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_3q2018_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_2q2018_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_1q2018_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_4q2017_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_3q2017_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_2q2017_cleaned.csv",
         "../cleaned_data/unzipped_data/PUDF_base1_1q2017_cleaned.csv"]

In [ ]:
outputs = ["../new_cleaned_data/PUDF_base1_4q2019_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_3q2019_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_2q2019_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_1q2019_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_4q2018_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_3q2018_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_2q2018_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_1q2018_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_4q2017_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_3q2017_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_2q2017_cleaned.zip",
         "../new_cleaned_data/PUDF_base1_1q2017_cleaned.zip"]

In [4]:
df = pd.read_csv(files[0])
df.columns

/var/folders/8t/39dh6vlx159_ntc59x13g12r0000gn/T/ipykernel_86586/346167791.py:1: DtypeWarning: Columns (0: SOURCE_OF_ADMISSION) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(files[0])

Index(['RECORD_ID', 'DISCHARGE', 'THCIC_ID', 'TYPE_OF_ADMISSION',
       'SOURCE_OF_ADMISSION', 'PAT_STATE', 'PAT_ZIP', 'PAT_COUNTRY',
       'PAT_COUNTY', 'PUBLIC_HEALTH_REGION', 'PAT_STATUS', 'SEX_CODE', 'RACE',
       'ETHNICITY', 'ADMIT_WEEKDAY', 'LENGTH_OF_STAY', 'PAT_AGE',
       'EMERGENCY_DEPT_FLAG', 'DIAG_CODES_OA', 'CODE_1', 'CODE_2', 'CODE_3',
       'CODE_4', 'CODE_5', 'CODE_6', 'CODE_7', 'CODE_8', 'CODE_9', 'CODE_10',
       'CODE_11', 'CODE_12', 'CODE_13', 'CODE_14', 'CODE_15', 'CODE_16',
       'CODE_17', 'CODE_18', 'CODE_19', 'CODE_20', 'CODE_21', 'CODE_22',
       'PAT_RURAL', 'PROVIDER_ZIP', 'PROVIDER_RURAL', 'PAT2PROV_DISTANCE'],
      dtype='str')

In [5]:
df[['DIAG_CODES_OA']].head()

                                       DIAG_CODES_OA
0                                            ['Z38']
1                                            ['R06']
2  ['R30', 'A41', 'J96', 'N39', 'I48', 'I50', 'R6...
3         ['R06', 'J96', 'J44', 'E87', 'J96', 'F17']
4  ['I10', 'I16', 'T86', 'N25', 'I12', 'N18', 'I2...

In [14]:
import pgeocode

nomi = pgeocode.Nominatim("us")

def zip_to_coords(zipcode):
    code = nomi.query_postal_code(str(zipcode))
    return code.latitude, code.longitude

In [37]:
sample_zip = df.sample().iloc[0]['DIAG_CODES_OA']
print(sample_zip, len(sample_zip))
print(type(sample_zip))

['G43', 'G43', 'E11', 'R00', 'T44', 'E66', 'I10', 'E78'] 56
<class 'str'>

In [89]:
import ast

def num_codes(z):
    if isinstance(z, list):
        return len(z)

    if pd.isna(z):
        return 0

    if isinstance(z, str):
        z = z.replace("nan", "None")
        return len(ast.literal_eval(z))

    return 0

In [112]:
df = pd.read_csv(files[0], low_memory=False)
df.head()

,RECORD_ID,DISCHARGE,THCIC_ID,TYPE_OF_ADMISSION,SOURCE_OF_ADMISSION,PAT_STATE,PAT_ZIP,PAT_COUNTRY,PAT_COUNTY,PUBLIC_HEALTH_REGION,...,CODE_17,CODE_18,CODE_19,CODE_20,CODE_21,CODE_22,PAT_RURAL,PROVIDER_ZIP,PROVIDER_RURAL,PAT2PROV_DISTANCE
0,320195613796,2019Q3,971000,4.0,5,TX,76542,US,27.0,7.0,...,0,0,0,0,1,0,0,76548,0,6.687711
1,320195641723,2019Q3,72000,1.0,1,TX,75972,US,405.0,5.0,...,0,1,0,0,0,0,1,75974,1,48.583918
2,320195641760,2019Q3,466000,3.0,1,TX,77351,US,373.0,5.0,...,0,1,0,0,0,0,1,77351,1,0.000000
3,320195641763,2019Q3,466000,1.0,1,TX,77360,US,373.0,5.0,...,0,1,0,0,0,0,1,77351,1,25.219532
4,320195641764,2019Q3,466000,1.0,1,TX,77369,US,291.0,6.0,...,0,1,1,0,0,0,0,77351,1,28.877323

In [110]:
new_df = clean_data(files[0])
new_df.head()

,RECORD_ID,THCIC_ID,TYPE_OF_ADMISSION,SOURCE_OF_ADMISSION,PUBLIC_HEALTH_REGION,PAT_STATUS,SEX_CODE,RACE,ETHNICITY,ADMIT_WEEKDAY,...,CODE_22,PAT_RURAL,PROVIDER_RURAL,PAT2PROV_DISTANCE,QUARTER,YEAR,PAT_LATITUDE,PAT_LONGITUDE,PROVIDER_LATITUDE,PROVIDER_LONGITUDE
0,320195613796,971000,4.0,5,7.0,1,M,4,2,7.0,...,0,0,0,6.687711,4,2019,31.0376,-97.6809,31.0286,-97.6115
1,320195641723,72000,1.0,1,5.0,1,F,4,2,2.0,...,0,1,1,48.583918,4,2019,31.5152,-94.1326,31.9408,-94.2488
3,320195641763,466000,1.0,1,5.0,1,F,4,2,4.0,...,0,1,1,25.219532,4,2019,30.8225,-95.1056,30.6829,-94.8976
4,320195641764,466000,1.0,1,6.0,1,M,4,2,3.0,...,0,0,1,28.877323,4,2019,30.4596,-94.7436,30.6829,-94.8976
7,320195641787,468000,2.0,1,10.0,1,M,4,2,2.0,...,0,0,1,291.115241,4,2019,31.8045,-105.9661,31.5813,-102.9003

In [111]:
new_df['SOURCE_OF_ADMISSION'].value_counts()

SOURCE_OF_ADMISSION
1    355167
2     93475
5     83704
4     44754
6      5802
D      3263
9      2172
8      1689
F       240
E       120
`        56
Name: count, dtype: int64

In [90]:
df['NUM_CODES'] = df['DIAG_CODES_OA'].apply(lambda z: num_codes(z))
df = df.drop(columns = 'DIAG_CODES_OA')

df.columns

Index(['RECORD_ID', 'DISCHARGE', 'THCIC_ID', 'TYPE_OF_ADMISSION',
       'SOURCE_OF_ADMISSION', 'PAT_STATE', 'PAT_ZIP', 'PAT_COUNTRY',
       'PAT_COUNTY', 'PUBLIC_HEALTH_REGION', 'PAT_STATUS', 'SEX_CODE', 'RACE',
       'ETHNICITY', 'ADMIT_WEEKDAY', 'LENGTH_OF_STAY', 'PAT_AGE',
       'EMERGENCY_DEPT_FLAG', 'CODE_1', 'CODE_2', 'CODE_3', 'CODE_4', 'CODE_5',
       'CODE_6', 'CODE_7', 'CODE_8', 'CODE_9', 'CODE_10', 'CODE_11', 'CODE_12',
       'CODE_13', 'CODE_14', 'CODE_15', 'CODE_16', 'CODE_17', 'CODE_18',
       'CODE_19', 'CODE_20', 'CODE_21', 'CODE_22', 'PAT_RURAL', 'PROVIDER_ZIP',
       'PROVIDER_RURAL', 'PAT2PROV_DISTANCE', 'NUM_CODES'],
      dtype='str')

In [98]:
df.iloc[2]['DIAG_CODES_OA']

"['R30', 'A41', 'J96', 'N39', 'I48', 'I50', 'R65', 'I11', 'N40', 'R33']"

In [126]:
def clean_data(file_name):
    df = pd.read_csv(file_name, low_memory= False)
    
    df = df.drop(columns = ['PAT_COUNTRY', 'PAT_STATE', 'PAT_COUNTY'])
    
    df['QUARTER'] = file_name[41:42]
    df['YEAR'] = file_name[43:47]
    df = df.drop(columns = 'DISCHARGE')
    
    nomi = pgeocode.Nominatim("us")

    df["zip_clean"] = (
        df["PAT_ZIP"]
        .astype(str)
        .str[:5]
        .str.zfill(5)
    )
    
    unique_zips = df["zip_clean"].dropna().unique()

    zip_lookup = nomi.query_postal_code(unique_zips)

    zip_lookup = zip_lookup[["postal_code", "latitude", "longitude"]]

    df = df.merge(
        zip_lookup,
        left_on="zip_clean",
        right_on="postal_code",
        how="left"
    )

    df = df.drop(columns = ['PAT_ZIP', 'zip_clean', 'postal_code'])
    df = df.rename(columns = {"latitude":"PAT_LATITUDE", "longitude" : "PAT_LONGITUDE"})
    
    df["zip_clean"] = (
        df["PROVIDER_ZIP"]
        .astype(str)
        .str[:5]
        .str.zfill(5)
    )
    
    unique_zips = df["zip_clean"].dropna().unique()

    zip_lookup = nomi.query_postal_code(unique_zips)

    zip_lookup = zip_lookup[["postal_code", "latitude", "longitude"]]

    df = df.merge(
        zip_lookup,
        left_on="zip_clean",
        right_on="postal_code",
        how="left"
    )
    
    df = df.drop(columns = ['PROVIDER_ZIP', 'zip_clean', 'postal_code'])
    df = df.rename(columns = {"latitude":"PROVIDER_LATITUDE", "longitude" : "PROVIDER_LONGITUDE"})
    
    df = df[df['PAT2PROV_DISTANCE'] > 0]
    
    df = df[df['TYPE_OF_ADMISSION'] != 9]
    
    df = df[df['SOURCE_OF_ADMISSION'] != "9"]
    
    return df